### ISSUE TITLE
Fixing frozen positions

### ISSUE THREAD

**Issue by sontn1988** [tradingstrategy-ai/trade-executor#280]
## Issue
When i tried to fix frozen positions as document: https://tradingstrategy.ai/docs/running/repair.html
It's not work. This is log:
```
docker-compose run $EXECUTOR_ID repair

2023-04-06 13:26:37 root                                               INFO     Reading strategy strategies/pancake-eth-usd-sma.py
2023-04-06 13:26:37 root                                               INFO     Strategy module strategies/pancake-eth-usd-sma.py, engine version 0.1
2023-04-06 13:26:37 tradeexecutor.state.store                          INFO     Loaded state from state/pancake-eth-usd-sma.json
2023-04-06 13:26:40 tradeexecutor.state.repair                         INFO     Repairing trades
2023-04-06 13:26:40 tradeexecutor.state.repair                         INFO     Strategy has 1 frozen positions
2023-04-06 13:26:40 tradeexecutor.state.repair                         INFO     Found a trade needing repair: <Sell #242 0.141189440487611938 ETH at 1712.523755920836, failed>
2023-04-06 13:26:40 tradeexecutor.state.repair                         INFO     Found 1 trades to be repaired
Needs repair: <Sell #242 0.141189440487611938 ETH at 1712.523755920836, failed>
Attempt to repair [y/n]Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/usr/src/trade-executor/tradeexecutor/cli/commands/repair.py", line 132, in repair
    report = repair_trades(
  File "/usr/src/trade-executor/tradeexecutor/state/repair.py", line 261, in repair_trades
    raise RepairAborted()
```

## Goal
Command will repair frozen positions

**Comment by AlexTheLion123** [comment]
@miohtama @sontn1988 Still relevant?
