### ISSUE TITLE
ETH-USD breakout deposit contract failure

### ISSUE THREAD

**Issue by kenkunz** [tradingstrategy-ai/trade-executor#615]
# Issue

Attempts to deposit funds to ETH-USD breakout strategy (`enzyme-polygon-eth-usdc`) fail with an error from the smart contract.

## Steps to reproduce

1. open [ETH-USD breakout on Uniswap v3](https://tradingstrategy.ai/strategies/enzyme-polygon-eth-usdc) overview page
2. Click the **Deposit** button
3. Connect a wallet (if you haven't already) with sufficient MATIC and USDC balance to make a deposit
4. Advance to the **Payment** step; enter 1 USDC and click **Make payment**
5. Sign the signature request in your wallet
6. Note the error:
   > **Error:** Payment confirmation from wallet account failed. Execution reverted for an unknown reason.

## Contract call details

The error occurs when calling @wagmi/core `prepareWriteContract` method:
https://github.com/tradingstrategy-ai/frontend/blob/b7aec3eb4a1bd4c9fd5db824eda02b965089358a/src/routes/wizard/deposit/payment/%2Bpage.svelte#L45-L50

Since the deposit step works on all other Enzyme vault strategies, this suggests that there's some issue with the `payment_forwarder` contract for this strategy.

Smart contract: [0xe3eaaba28b03d873304958eb30f412b6ccd4016c](https://polygonscan.com/address/0xe3eaaba28b03d873304958eb30f412b6ccd4016c)

## Sample error message

Returned by `viem`:

```
ContractFunctionExecutionError: Execution reverted for an unknown reason.

Raw Call Arguments:
  from:  0xEFD90a79feE79aba176A7E1B0E101193fb7d7bda
  to:    0xE3eAabA28B03d873304958EB30f412b6CCd4016c
  data:  0x7cc4040b000000000000000000000000efd90a79fee79aba176a7e1b0e101193fb7d7bda000000000000000000000000e3eaaba28b03d873304958eb30f412b6ccd4016c00000000000000000000000000000000000000000000000000000000000f4240000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000652d77ec1223eaddd1d0c09e0a0b28543498e5d6ee6bbd550d1c0afe14954e143323694d000000000000000000000000000000000000000000000000000000000000001b7acc84141dd012e10d0acfd661d28f459de6dcf19b729a91414f9d284e5018fc21678e691cd7abec37dc926cd731efe6dd6ff0845e6359103c83d93eb8e61bda0000000000000000000000000000000000000000000000000000000000000001
 
Contract Call:
  address:   0xE3eAabA28B03d873304958EB30f412b6CCd4016c
  function:  buySharesOnBehalfUsingTransferWithAuthorization(address from, address to, uint256 value, uint256 validAfter, uint256 validBefore, bytes32 nonce, uint8 v, bytes32 r, bytes32 s, uint256 minSharesQuantity)
  args:      (0xEFD90a79feE79aba176A7E1B0E101193fb7d7bda, 0xE3eAabA28B03d873304958EB30f412b6CCd4016c, 1000000, 0, 1697478636, 0x1223eaddd1d0c09e0a0b28543498e5d6ee6bbd550d1c0afe14954e143323694d, 27, 0x7acc84141dd012e10d0acfd661d28f459de6dcf19b729a91414f9d284e5018fc, 0x21678e691cd7abec37dc926cd731efe6dd6ff0845e6359103c83d93eb8e61bda, 1)
  sender:    0xEFD90a79feE79aba176A7E1B0E101193fb7d7bda

Docs: https://viem.sh/docs/contract/simulateContract.html
Details: execution reverted
Version: viem@1.10.12
    at getContractError (getContractError.ts:56:10)
    at simulateContract (simulateContract.ts:159:11)
    at async prepareWriteContract (chunk-LAFZBYO7.js:2078:31)
    at async confirmPayment (+page.svelte:45:18)
```

**Comment by kenkunz** [comment]
Per @miohtama:
> ETH-USDC strategy VaultUSDCPaymentForwarder contract is old version
> I will deploy a new one that supports both `buySharesOnBehalfUsingTransferWithAuthorization`  and `buySharesOnBehalfUsingReceiveWithAuthorization`
> ...
> this is the new payment forwarder https://polygonscan.com/address/0x057bfE6A467e37636462AA92733C04a8D05c3f74 - should be reflected in the trade executor configs now

Once this new address was reflected in the `metadata` response, I re-tested and verified that the issue is resolved:

![image](https://github.com/tradingstrategy-ai/trade-executor/assets/35901/8ebc081c-5b7e-47a4-b7e4-cad040753cd7)
