### ISSUE TITLE
Kaleido backend hanging

### ISSUE THREAD

**Issue by miohtama** [tradingstrategy-ai/trade-executor#699]
Plotly's Kaleido backend is hanging when generating strategy charts.

Related issue https://github.com/plotly/Kaleido/issues/42#issuecomment-695199437

Related traceback:

```
enzyme-polygon-multipair  | 2023-12-01 09:18:00 apscheduler.scheduler                              WARNING  Execution of job "ExecutionLoop.run_live.<locals>.live_trigger_checks (trigger: interval[0:03:00], next run at: 2023-12-01 09:18:00 UTC)" skipped: maximum number of running instances reached (1)
enzyme-polygon-multipair  | 2023-12-01 09:18:08 apscheduler.scheduler                              INFO     Scheduler has been shut down
enzyme-polygon-multipair  | 2023-12-01 09:18:08 root                                               ERROR    trade-executor enzyme-polygon-multipair killed by watchdog or CTRL+C requested: . Shutting down.
enzyme-polygon-multipair  | 2023-12-01 09:18:08 root                                               ERROR    If you are running manually press CTRL+C again to quit
enzyme-polygon-multipair  | 2023-12-01 09:18:09 root                                               ERROR    
enzyme-polygon-multipair  | Traceback (most recent call last):
enzyme-polygon-multipair  |   File "/usr/src/trade-executor/tradeexecutor/cli/commands/start.py", line 460, in start
enzyme-polygon-multipair  |     loop.run_with_state(state)
enzyme-polygon-multipair  |   File "/usr/src/trade-executor/tradeexecutor/cli/loop.py", line 1251, in run_with_state
enzyme-polygon-multipair  |     return self.run_live(state)
enzyme-polygon-multipair  |   File "/usr/src/trade-executor/tradeexecutor/cli/loop.py", line 1142, in run_live
enzyme-polygon-multipair  |     scheduler.start()
enzyme-polygon-multipair  |   File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/blocking.py", line 21, in start
enzyme-polygon-multipair  |     self._main_loop()
enzyme-polygon-multipair  |   File "/usr/local/lib/python3.10/site-packages/apscheduler/schedulers/blocking.py", line 30, in _main_loop
enzyme-polygon-multipair  |     self._event.wait(wait_seconds)
enzyme-polygon-multipair  |   File "/usr/local/lib/python3.10/threading.py", line 607, in wait
enzyme-polygon-multipair  |     signaled = self._cond.wait(timeout)
enzyme-polygon-multipair  |   File "/usr/local/lib/python3.10/threading.py", line 324, in wait
enzyme-polygon-multipair  |     gotit = waiter.acquire(True, timeout)
enzyme-polygon-multipair  | KeyboardInterrupt
enzyme-polygon-multipair  | Thread 0x00007f6b9c0ad700 (most recent call first):
enzyme-polygon-multipair  |   File "/usr/local/lib/python3.10/site-packages/kaleido/scopes/base.py", line 308 in _perform_transform
enzyme-polygon-multipair  |   File "/usr/local/lib/python3.10/site-packages/kaleido/scopes/plotly.py", line 153 in transform
enzyme-polygon-multipair  |   File "/usr/local/lib/python3.10/site-packages/plotly/io/_kaleido.py", line 143 in to_image
enzyme-polygon-multipair  |   File "/usr/local/lib/python3.10/site-packages/plotly/io/_kaleido.py", line 266 in write_image
enzyme-polygon-multipair  |   File "/usr/local/lib/python3.10/site-packages/plotly/basedatatypes.py", line 3841 in write_image
enzyme-polygon-multipair  |   File "/usr/src/trade-executor/tradeexecutor/visual/image_output.py", line 34 in render_plotly_figure_as_image_file
enzyme-polygon-multipair  |   File "/usr/src/trade-executor/tradeexecutor/strategy/pandas_trader/runner.py", line 190 in get_image_and_dark_image
enzyme-polygon-multipair  |   File "/usr/src/trade-executor/tradeexecutor/strategy/pandas_trader/runner.py", line 181 in get_small_images
enzyme-polygon-multipair  |   File "/usr/src/trade-executor/tradeexecutor/strategy/pandas_trader/runner.py", line 159 in update_strategy_thinking_image_data
enzyme-polygon-multipair  |   File "/usr/src/trade-executor/tradeexecutor/strategy/pandas_trader/runner.py", line 140 in refresh_visualisations
enzyme-polygon-multipair  |   File "/usr/src/trade-executor/tradeexecutor/strategy/pandas_trader/runner.py", line 232 in report_strategy_thinking
enzyme-polygon-multipair  |   File "/usr/src/trade-executor/tradeexecutor/strategy/runner.py", line 639 in tick
enzyme-polygon-multipair  |   File "/usr/src/trade-executor/tradeexecutor/cli/loop.py", line 460 in tick
enzyme-polygon-multipair  |   File "/usr/src/trade-executor/tradeexecutor/cli/loop.py", line 1005 in live_cycle
enzyme-polygon-multipair  |   File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125 in run_job
enzyme-polygon-multipair  |   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58 in run
enzyme-polygon-multipair  |   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 83 in _worker
enzyme-polygon-multipair  |   File "/usr/local/lib/python3.10/threading.py", line 953 in run
enzyme-polygon-multipair  |   File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
enzyme-polygon-multipair  |   File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap
```

**Comment by miohtama** [comment]
It launches a Chromium in the subprocess and tries to take a screenshot. It is likely the subprocess has crashed and IO with the crashed subprocess hangs:

```python
    def _perform_transform(self, data, **kwargs):
        """
        Transform input data using the current scope, returning dict response with error code
        whether successful or not.

        :param data: JSON-serializable object to be converted
        :param kwargs: Transform arguments for scope
        :return: Dict of response from Kaleido executable, whether successful or not
        """
        # Ensure that kaleido subprocess is running
        self._ensure_kaleido()

        # Perform export
        export_spec = self._json_dumps(dict(kwargs, data=data)).encode('utf-8')

        # Write to process and read result within a lock so that can be
        # sure we're reading the response to our request
        with self._proc_lock:
            # Reset _std_error buffer
            self._std_error = io.BytesIO()

            # Write and flush spec
            self._proc.stdin.write(export_spec)
            self._proc.stdin.write("\n".encode('utf-8'))
            self._proc.stdin.flush()
            response = self._proc.stdout.readline()

        response_string = response.decode('utf-8')
        if not response_string:
            message = (
                    "Transform failed. Error stream:\n\n" +
                    self._get_decoded_std_error()
            )
            raise ValueError(message)
        try:
            response = json.loads(response_string)
        except JSONDecodeError:
            print("Invalid JSON: " + repr(response_string))
            raise

        return response
```
